name: Deploy Santawishist to Azure App Service
on:
  workflow_dispatch:
    inputs:
      region:
        description: 'Azure Region to deploy to, e.g. westeurope, eastus.'
        required: true
        default: ''
      tag:
        description: 'Container tag to deploy, this is the short git commit id.'
        required: true
        default: '<short-commit-id>'

jobs:
  update_app_service:
    name: Update App Service container image
    runs-on: ubuntu-latest

    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.SANTAWISHLIST_AAD_SP }}

    - name: Update App Service
      uses: azure/CLI@v1
      with:
        azcliversion: 2.15.1
        inlineScript: |
          az webapp config container set \
          --name santawishlist-${{ github.event.inputs.region }}-app \
          --resource-group santawishlist-${{ github.event.inputs.region }}-rg \
          --docker-registry-server-url 'https://${{ secrets.SANTAWISHLIST_ACR }}.azurecr.io' \
          --docker-registry-server-user ${{ secrets.SANTAWISHLIST_ACR }} \
          --docker-registry-server-password ${{ secrets.SANTAWISHLIST_ACR_PASSWORD }} \
          --docker-custom-image-name ${{ secrets.SANTAWISHLIST_ACR }}.azurecr.io/santawishlist-app:${{ github.event.inputs.tag }}