
name: Destroy environmnet

on:
  workflow_dispatch:

jobs:
  plan-terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - uses: actions/checkout@main

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.2

      - name: Initialise terraform
        id: init
        run: |
          cd terraform
          terraform init

      - name: Destroy
        run: |
          cd terraform
          terraform destroy -auto-approve
        id: destroy